name: amazon runner
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - name: start build
          run: echo "hello cloudgurus"
      
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: start test
        run: echo "testing phase"
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: start deploy
        run: echo "deployment phase"
      
    

  
