name: amazon runner
on:
  push:
    branches: [main]
  pull_requests:
    branches: [main]
    
jobs:
  build:
      runs-on: Linux
      steps:
        - name: start build
          run: echo "hello cloudgurus"
      
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: start test
        run: echo "testing phase"
  
  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: start deploy
        run: echo "deployment phase"
      
    

  
