name: amazon runner
on:
  push:
    branches: [main]
  pull_requests:
    branches: [main]
    
jobs:
  build:
      uses: alpine
      steps:
        - name: start build
          run: echo "hello cloudgurus"
      
  test:
    uses: alpine
    needs: build
    steps:
      - name: start test
        run: echo "testing phase"
  
  deploy:
    uses: alpine
    needs: test
    steps:
      - name: start deploy
        run: echo "deployment phase"
      
    

  
